version: "4"
services:
  webserver:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=ascom@ufac.br"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - web
      - internal
      
  agencia:
    image: ghcr.io/plonegovbr/portal:latest
    ports:
      - '3002:3000'
    restart: always
    labels:
      - traefik.enable=true
      #service
      - traefik.http.services.plone-agencia.loadbalancer.server.port=3001
      # HOST: main
      - traefik.http.routers.agencia.rule=Host(`agencia.localhost`)
      - traefik.http.routers.agencia.service=plone-agencia
      - traefik.http.routers.agencia.middlewares=gzip
    environment:
      # These are needed in a Docker environment since the
      # routing needs to be amended. You can point to the
      # internal network alias.
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/agencia
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/agencia
    depends_on:
      - backend
    volumes:
      - ./frontend/src/addons:/src/addons
      
  portal:
    image: ghcr.io/plonegovbr/portal:latest
    ports:
      - '3001:3000'
    restart: always
    labels:
      - traefik.enable=true
      #service
      - traefik.http.services.plone-portal.loadbalancer.server.port=3000
      # HOST: main
      - traefik.http.routers.portal.rule=Host(`portal.localhost`)
      - traefik.http.routers.portal.service=plone-portal
      - traefik.http.routers.portal.middlewares=gzip
    environment:
      # These are needed in a Docker environment since the
      # routing needs to be amended. You can point to the
      # internal network alias.
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/portal
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/portal
    depends_on:
      - backend
    volumes:
      - ./frontend/src/addons:/src/addons
      
  
  backend:
    image: plone/plone-backend:6.0.12
    environment:
      SITE: Plone
      CORS_ALLOW_ORIGIN: '*'
      ADDONS: "collective.exportimport"
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plone-http.rule=Host(`www3.ufac.br`)"
      - "traefik.http.routers.plone-http.entrypoints=web"
      - "traefik.http.services.plone-backend.loadbalancer.server.port=8080"
    volumes:
      - data:/data
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  data: