version: "4"
services:
  webserver:
    image: traefik:v2.9
    ports:
      - "81:80"
      - "443:443"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesresolvers.myresolver.acme.email=ascom@ufac.br"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/local/plone/cert:/certs

  agencia:
    image: ghcr.io/plonegovbr/portal:latest
    ports:
      - '3002:3000'
    restart: always
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.plone-agencia.loadbalancer.server.port=3002
      # HOST
      - traefik.http.routers.agencia.rule=Host(`agencia.localhost`)
      - traefik.http.routers.agencia.entrypoints=websecure
      - traefik.http.routers.agencia.tls=true
      - traefik.http.routers.agencia.tls.certresolver=myresolver
      - traefik.http.routers.agencia.middlewares=gzip
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/agencia
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/agencia
    depends_on:
      - backend
    volumes:
      - ./frontend/src/addons:/src/addons

  portal:
    image: ghcr.io/plonegovbr/portal:latest
    ports:
      - '3001:3000'
    restart: always
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.plone-portal.loadbalancer.server.port=3001
      # HOST
      - traefik.http.routers.portal-portal.rule=Host(`portal.localhost`)
      - traefik.http.routers.portal-portal.entrypoints=websecure
      - traefik.http.routers.portal-portal.tls=true
      - traefik.http.routers.portal-portal.tls.certresolver=myresolver
      - traefik.http.routers.portal-portal.middlewares=gzip
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/portal
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/portal
    depends_on:
      - backend
    volumes:
      - ./frontend/src/addons:/src/addons

  editais:
    image: plone/volto:latest
    ports:
      - '3003:3000'
    restart: always
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.plone-editais.loadbalancer.server.port=3003
      # HOST
      - traefik.http.routers.portal-editais.rule=Host(`www3.ufac.br`)
      - traefik.http.routers.portal-editais.entrypoints=websecure
      - traefik.http.routers.portal-editais.tls=true
      - traefik.http.routers.portal-editais.tls.certresolver=myresolver
      - traefik.http.routers.portal-editais.middlewares=gzip
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/editais
      RAZZLE_API_PATH: http://www3.ufac.br/editais
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/editais
    depends_on:
      - backend
    volumes:
      - ./frontend/src/addons:/src/addons

  backend:
    image: plone/plone-backend:6.0.12
    environment:
      SITE: Plone
      CORS_ALLOW_ORIGIN: '*'
      ADDONS: "collective.exportimport"
    ports:
      - 80:8080
    labels:
      - traefik.enable=true
      - traefik.constraint-label=public
      # Service
      - traefik.http.services.svc-backend.loadbalancer.server.port=8080
      ## Virtual Host Monster for /++api++/
      - "traefik.http.middlewares.mw-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
      - "traefik.http.middlewares.mw-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/http/universidade.localhost/Plone/++api++/VirtualHostRoot$$1"
      ## Virtual Host Monster for /ClassicUI/
      - "traefik.http.middlewares.mw-backend-vhm-ui.replacepathregex.regex=^/ClassicUI($$|/.*)"
      - "traefik.http.middlewares.mw-backend-vhm-ui.replacepathregex.replacement=/VirtualHostBase/http/universidade.localhost/Plone/VirtualHostRoot/_vh_ClassicUI$$1"
      # Router: Internal /++api++/
      - traefik.http.routers.rt-backend-api-internal.rule=Host(`www3.ufac.br`) && PathPrefix(`/++api++`)
      - traefik.http.routers.rt-backend-api-internal.entrypoints=web
      - traefik.http.routers.rt-backend-api-internal.service=svc-backend
      - traefik.http.routers.rt-backend-api-internal.middlewares=gzip,mw-backend-vhm-api
      # Router: Internal /ClassicUI/
      - traefik.http.routers.rt-backend-ui-internal.rule=Host(`www3.ufac.br`) && PathPrefix(`/ClassicUI`)
      - traefik.http.routers.rt-backend-ui-internal.entrypoints=web
      - traefik.http.routers.rt-backend-ui-internal.service=svc-backend
      - traefik.http.routers.rt-backend-ui-internal.middlewares=gzip,mw-backend-vhm-ui
      # Router para HTTPS
      - traefik.http.routers.seusite.rule=Host(`www3.ufac.br`)
      - traefik.http.routers.seusite.entrypoints=websecure
      - traefik.http.routers.seusite.tls=true
      - traefik.http.routers.seusite.tls.certresolver=myresolver
      # Redirect HTTP -> HTTPS
      - "traefik.http.middlewares.redirect-to-editais.redirectregex.regex=^http://www3.ufac.br/?$$"
      - "traefik.http.middlewares.redirect-to-editais.redirectregex.replacement=http://www3.ufac.br/editais"
      - "traefik.http.middlewares.redirect-to-editais.redirectregex.permanent=true"
      - "traefik.http.routers.seusite.middlewares=redirect-to-editais"
    volumes:
      - data:/data

volumes:
  data:
